### ISSUE TITLE
How to deny this seeker? 

### ISSUE THREAD

**Issue by Bloodiko** [DAMcraft/MeteorServerSeeker#24]
I don't want my server to be found. 

It's a private server for a limited range of users. 
Let me block this from appearing in search results. 

Also how come there is just the "Disconnect" listed in the logs of the server, but not the Connect?? 

And why is the user being used to find the server not in the logs either, so that I can block it ?

**Comment by Paddyk45** [comment]
> Also how come there is just the "Disconnect" listed in the logs of the server, but not the Connect??
The bot disconnects before fully logging in, which makes the logs not show the connect message

**Comment by DAMcraft** [comment]
You can drop all packets from 109.123.240.84, or if that's not possible, message me on discord, @damcraft.de
