### ISSUE TITLE
crash when disconnect from server

### ISSUE THREAD

**Issue by Reader10** [DAMcraft/MeteorServerSeeker#29]
when i try to disconnect from a server it crashes and is only when this mod is loaded is says "error code -1"

**Comment by Reader10** [comment]
https://mclo.gs/snVV9I2

**Comment by Reader10** [comment]
it only happens after i verify in discord, if i try to disconnect from a server before verifying in discord is normal and nothing happens but it crash after i verify in discord and try to disconnect

**Comment by Paddyk45** [comment]
Can you replace your current MeteorServerSeeker jar with this one and tell if it fixes it? https://pub.microbin.eu/file/spider-bison-lion

**Comment by Reader10** [comment]
link shows 502 error bad gateway

**Comment by DAMcraft** [comment]
@Reader10 this should be fixed with the new dev build. If the issue still appears, just reopen the issue :)
