### ISSUE TITLE
nice iq

### ISSUE THREAD

**Issue by master7720** [DAMcraft/MeteorServerSeeker#34]
https://github.com/DAMcraft/MeteorServerSeeker/releases/tag/latest

who uses virus total to check jars just run theia or something

**Comment by swpq** [comment]
nice iq virustotal is more secure in terms of that stfu no name omfg

**Comment by master7720** [comment]
> nice iq virustotal is more secure in terms of that stfu no name omfg

not a no name and virustotal is shit for checking jars
