### ISSUE TITLE
bug: "Error: 1034 (HY000): Index for table 'player_history' is corrupt" after pressing "Get players" button

### ISSUE THREAD

**Issue by parknich** [DAMcraft/MeteorServerSeeker#36]
![image](https://github.com/DAMcraft/MeteorServerSeeker/assets/45834520/c518cbca-3a38-4d26-aad1-52243c62c2cc)
I do not know why this is happening, I've tried using the mod in a fresh .minecraft folder after this happened, and it did not resolve it.
This bug happens after pressing "Get players" and then whenever i try to search for a player or view server info, it shows the same message permanently.

**Comment by DAMcraft** [comment]
This is a database issue and has been resolved.
