### ISSUE TITLE
[idk wat happen

### ISSUE THREAD

**Issue by Foxylol121** [DAMcraft/MeteorServerSeeker#40]
![image (1)](https://github.com/DAMcraft/MeteorServerSeeker/assets/92961701/1638b8e0-3dd6-4d0d-b671-5359bf6a5fdc)
![image (2)](https://github.com/DAMcraft/MeteorServerSeeker/assets/92961701/25e0ddb5-18cf-4340-b676-21c176148573)
![image (3)](https://github.com/DAMcraft/MeteorServerSeeker/assets/92961701/e4a79f5d-6031-40d1-8e84-0b768270ab92)
he doesn’t want to log in and just gives an error(

**Comment by DAMcraft** [comment]
What version are you using? This is most likely a bug on any version lower than 4.3.1

**Comment by Foxylol121** [comment]
![Uploading image (4).jpg…]()

**Comment by Foxylol121** [comment]
![image (4)](https://github.com/DAMcraft/MeteorServerSeeker/assets/92961701/3503bd86-4061-4720-a4f1-4e976486e33c)

**Comment by Foxylol121** [comment]
![Uploading image (5).jpg…]()

**Comment by Foxylol121** [comment]
![image (5)](https://github.com/DAMcraft/MeteorServerSeeker/assets/92961701/671bad5d-fb77-427b-a767-ef66e6b7e708)

**Comment by DAMcraft** [comment]
You are using 4.2.0. Please update to the newest version.

**Comment by Foxylol121** [comment]
k second

**Comment by Foxylol121** [comment]
exactly the same problem
![image (6)](https://github.com/DAMcraft/MeteorServerSeeker/assets/92961701/69aa19d4-d601-42e5-82ab-8a186c057878)

**Comment by DAMcraft** [comment]
Should be fixed now! Was an error on our end
