### ISSUE TITLE
i cant join

### ISSUE THREAD

**Issue by IXEN-s** [DAMcraft/MeteorServerSeeker#44]
hello i cant join ur discord my user is unknownxenor idk why but please let me join

**Comment by DAMcraft** [comment]
oh would you look at that :/
your discord account @unknownxenor (ID 1120732621807300698, previously known as "unknown36664") got banned on 2023-09-28 after you started doxxing server members

![grafik](https://github.com/user-attachments/assets/5c631736-0250-472c-ab5a-62f70abdad0e)
![grafik](https://github.com/user-attachments/assets/06498dc0-48c6-4fe9-a717-ee56752814cc)

**Comment by nikolan123** [comment]
😭😭
