### ISSUE TITLE
Auth button not open browser

### ISSUE THREAD

**Issue by Nekiplay** [DAMcraft/MeteorServerSeeker#9]
Auth button not open browser in Linux

**Comment by Paddyk45** [comment]
Try opening this in your browser: https://discord.com/oauth2/authorize?client_id=1087083964432404590&redirect_uri=http%3A%2F%2F127.0.0.1%3A7637%2F&response_type=code&scope=identify

**Comment by Nekiplay** [comment]
> Try opening this in your browser: https://discord.com/oauth2/authorize?client_id=1087083964432404590&redirect_uri=http%3A%2F%2F127.0.0.1%3A7637%2F&response_type=code&scope=identify while it shows "Please authenticate with Discord in your browser"

Its work
